name: Deploy PR previews

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-preview:
    uses: PazerOP/pr-preview-action/.github/workflows/preview.yml@master
    secrets: inherit
